# Generated by Django 6.1.1 on 2026-09-04 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('author', models.CharField(blank=True, max_length=255, verbose_name='Автор')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('language', models.CharField(default='ru', max_length=10, verbose_name='Язык')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Обложка')),
                ('source_file', models.FileField(upload_to='books/', verbose_name='Файл книги')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=280, unique=True, verbose_name='Адрес')),
                ('status', models.CharField(choices=[('pending', 'Ожидает разбора'), ('ready', 'Готова к чтению'), ('error', 'Ошибка разбора')], default='pending', max_length=20, verbose_name='Статус')),
                ('parse_error', models.TextField(blank=True, verbose_name='Текст ошибки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлена')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to=settings.AUTH_USER_MODEL, verbose_name='Кто загрузил')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядковый номер')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Текст главы (HTML)')),
                ('char_count', models.PositiveIntegerField(default=0, verbose_name='Символов')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='reader.book', verbose_name='Книга')),
            ],
            options={
                'verbose_name': 'Глава',
                'verbose_name_plural': 'Главы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ReadingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scroll_ratio', models.FloatField(default=0.0, verbose_name='Прокрутка внутри главы (0..1)')),
                ('percent', models.FloatField(default=0.0, verbose_name='Прочитано книги, %')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='reader.book', verbose_name='Книга')),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_entries', to='reader.chapter', verbose_name='Глава')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_progress', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Прогресс чтения',
                'verbose_name_plural': 'Прогресс чтения',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='chapter',
            constraint=models.UniqueConstraint(fields=('book', 'order'), name='unique_chapter_order'),
        ),
        migrations.AddConstraint(
            model_name='readingprogress',
            constraint=models.UniqueConstraint(fields=('user', 'book'), name='unique_progress_per_book'),
        ),
    ]
