# Generated by Django 6.1.1 on 2026-09-06 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0002_alter_book_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=90, unique=True, verbose_name='Адрес')),
                ('position', models.PositiveIntegerField(default=100, verbose_name='Порядок в списке')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='books', to='reader.category', verbose_name='Категории'),
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('planned', 'В планах'), ('reading', 'Читаю сейчас'), ('finished', 'Прочитано')], max_length=20, verbose_name='Статус')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='В избранном')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelf_entries', to='reader.book', verbose_name='Книга')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelf', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Полка',
                'verbose_name_plural': 'Полки пользователей',
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'book'), name='unique_shelf_per_book')],
            },
        ),
    ]
