# Generated by Django 6.1.1 on 2026-09-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0003_category_book_categories_shelf'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='total_chars',
            field=models.PositiveIntegerField(default=0, verbose_name='Объём, символов'),
        ),
    ]
