# Generated by Django 6.1.1 on 2026-09-07 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0004_book_total_chars'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='search_text',
            field=models.CharField(blank=True, db_index=True, max_length=520, verbose_name='Поисковая строка'),
        ),
    ]
