# Generated by Django 6.1.1 on 2026-09-07 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0006_sync_shelf_from_progress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст цитаты')),
                ('note', models.TextField(blank=True, verbose_name='Заметка')),
                ('scroll_ratio', models.FloatField(default=0.0, verbose_name='Позиция в главе (0..1)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Сохранена')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='reader.book', verbose_name='Книга')),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='reader.chapter', verbose_name='Глава')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Цитата',
                'verbose_name_plural': 'Цитаты',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'chapter'], name='reader_quot_user_id_339bbf_idx')],
            },
        ),
    ]
