# Generated by Django 6.1.1 on 2026-09-10 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from reader.genres import GENRES


def assign_codes(apps, schema_editor):
    """Проставляет коды жанров уже существующим категориям.

    Все они были созданы русскими и без кода. Опознаём их по названию и
    помечаем языком «ru» — иначе ограничение уникальности «код + язык»
    не применится: у всех строк код остался бы одинаковым.
    """
    Category = apps.get_model('reader', 'Category')
    by_russian_name = {russian: code for code, russian, _ in GENRES}

    seen = set()
    for category in Category.objects.all():
        code = by_russian_name.get(category.name)
        if code is None or code in seen:
            # Название не из справочника или такой жанр уже есть —
            # оставлять нельзя, ограничение не пропустит дубли.
            category.delete()
            continue
        seen.add(code)
        category.code = code
        category.language = 'ru'
        category.save(update_fields=['code', 'language'])


def noop(apps, schema_editor):
    """Откат не нужен: миграция только дозаполняет коды."""


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0007_quote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название книги')),
                ('author', models.CharField(blank=True, max_length=255, verbose_name='Автор')),
                ('genre', models.CharField(blank=True, max_length=255, verbose_name='Жанр или тема')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_work', 'В работе'), ('done', 'Добавлена'), ('rejected', 'Отклонена')], default='new', max_length=20, verbose_name='Статус')),
                ('admin_note', models.TextField(blank=True, verbose_name='Заметка администратора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
            ],
            options={
                'verbose_name': 'Заказ книги',
                'verbose_name_plural': 'Заказы книг',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['language', 'position', 'name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AddField(
            model_name='category',
            name='code',
            field=models.SlugField(default='other', max_length=40, verbose_name='Код жанра'),
        ),
        migrations.AddField(
            model_name='category',
            name='language',
            field=models.CharField(choices=[('ru', 'Русские'), ('en', 'Английские')], default='ru', max_length=5, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=80, verbose_name='Название'),
        ),
        # Коды нужно проставить ДО ограничения: иначе все существующие
        # категории останутся с кодом «other» и оно не применится.
        migrations.RunPython(assign_codes, noop),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('code', 'language'), name='unique_category_per_language'),
        ),
        migrations.AddField(
            model_name='bookrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_requests', to=settings.AUTH_USER_MODEL, verbose_name='Заказчик'),
        ),
    ]
