# Generated by Django 6.1.1 on 2026-09-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0008_bookrequest_alter_category_options_category_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Язык'),
        ),
    ]
