# Generated by Django 6.1.1 on 2026-09-10 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0009_alter_book_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
    ]
