# Generated by Django 6.1.1 on 2026-09-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0010_alter_bookrequest_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gutenberg_id', models.PositiveIntegerField(unique=True, verbose_name='Номер в Gutenberg')),
                ('title', models.CharField(max_length=500, verbose_name='Название')),
                ('authors', models.CharField(blank=True, max_length=500, verbose_name='Авторы')),
                ('language', models.CharField(blank=True, max_length=20, verbose_name='Язык')),
                ('subjects', models.TextField(blank=True, verbose_name='Темы')),
                ('search_text', models.CharField(db_index=True, max_length=1000, verbose_name='Поисковая строка')),
            ],
            options={
                'verbose_name': 'Запись каталога',
                'verbose_name_plural': 'Каталог Gutenberg',
                'ordering': ['title'],
            },
        ),
    ]
