# Generated by Django 6.0.6 on 2026-09-11 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0011_catalogentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Дата')),
                ('seconds', models.PositiveIntegerField(default=0, verbose_name='Время на сайте, секунд')),
                ('visits', models.PositiveIntegerField(default=1, verbose_name='Заходов за день')),
                ('beats', models.PositiveIntegerField(default=0, verbose_name='Сигналов получено')),
                ('last_page', models.CharField(blank=True, max_length=300, verbose_name='Последняя страница')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='Последний сигнал')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'День активности',
                'verbose_name_plural': 'Активность пользователей',
                'ordering': ['-date', '-seconds'],
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='unique_activity_per_day')],
            },
        ),
    ]
