"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Читаем секреты из файла .env — в код и в git они не попадают.
# Пока пакет не установлен, проект работает, просто без ключа.
try:
    from dotenv import load_dotenv

    load_dotenv(BASE_DIR / '.env')
except ImportError:
    pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-#p_n&8n6s^&&x&tr^2p^zg^e-6)(r-$miks(=94bw=@9f+^o2c'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Наши приложения
    'reader',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # Определяет язык интерфейса: сначала выбор пользователя из сессии,
    # потом заголовок браузера, потом LANGUAGE_CODE. Место в списке важно:
    # после сессий (иначе нечего читать) и до Common.
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'reader.context_processors.pending_orders',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'ru'

# Языки интерфейса. Русский — исходный: тексты в шаблонах написаны на нём,
# поэтому для него перевод не нужен.
LANGUAGES = [
    ('ru', 'Русский'),
    ('uz', 'Oʻzbekcha'),
    ('en', 'English'),
]

LOCALE_PATHS = [BASE_DIR / 'locale']

# Замени на свой пояс, например: 'Asia/Tashkent', 'Europe/Moscow', 'Asia/Almaty'
TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']   # где мы пишем свои CSS/JS
STATIC_ROOT = BASE_DIR / 'staticfiles'     # куда всё соберётся для продакшена

# Media: файлы, которые загружает пользователь (книги, обложки)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Claude API
ANTHROPIC_API_KEY = os.environ.get('ANTHROPIC_API_KEY', '')
AI_RATE_LIMIT_PER_MINUTE = 15   # запросов к модели на пользователя в минуту

# Нет ключа — работаем на заглушке. Появится ключ в .env — переключение
# произойдёт само, менять код не нужно. AI_MOCK=1 форсирует демо-режим.
AI_MOCK = os.environ.get('AI_MOCK') == '1' or not ANTHROPIC_API_KEY
AI_MOCK_DELAY = 0.4             # секунд: имитация задержки сети

# Аутентификация: куда отправлять пользователя после входа и выхода
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'reader:book_list'
LOGOUT_REDIRECT_URL = 'reader:book_list'

# Максимальный размер загружаемого файла — 50 МБ
DATA_UPLOAD_MAX_MEMORY_SIZE = 50 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 50 * 1024 * 1024


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
